[profile.default]
src = "src/v0.1"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
solc_version = "0.8.24"
fs_permissions=[{ access="write", path="./"}]


[profile.default.env]
private_key="$PRIVATE_KEY"
baseSepolia="https://sepolia.base.org"
mainnet="https://eth-mainnet.g.alchemy.com/v2/$ALCHEMY_API_KEY"
base="https://mainnet.base.org"
doma_testnet="https://rpc-testnet.doma.xyz/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
