[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions=[{ access="write", path="./"}]


[env]
private_key="$PRIVATE_KEY"
baseSepolia="https://sepolia.base.org"
mainnet="https://eth-mainnet.g.alchemy.com/v2/$ALCHEMY_API_KEY"
base="https://mainnet.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
